apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    metrics = ":9999"
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://104.154.130.94/ci/"
      token = "46b91baa5d058f0d26696cff7244a1"
      executor = "kubernetes"
      environment = ["DOCKER_DRIVER=overlay", "DOCKER_HOST=tcp://localhost:2375"]

      [runners.kubernetes]
        image = "docker:latest"
        privileged = true
